[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
allways_swap_manager = "AKgfVK8zJVHuZwttdjU2CPykaHyTAvw5r9FUFUpM74JU"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/allways-dev.json"

[scripts]
test = "cargo test"

[hooks]
