[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
allways_swap_manager = "BtVm5a1hKvMrrEHQ876Ev23dYVZAkWpYkf86VZi3z1Li"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/allways-dev.json"

[scripts]
test = "cargo test"

[hooks]
