pub mod admin;
pub mod close_stale_claim;
pub mod confirm_swap;
pub mod deactivate;
pub mod extend_reservation;
pub mod extend_timeout;
pub mod initialize;
pub mod mark_fulfilled;
pub mod open_or_request;
pub mod post_collateral;
pub mod remove_quote;
pub mod resolve_pool;
pub mod set_quote;
pub mod submit_swap_claim;
pub mod timeout_swap;
pub mod vote_activate;
pub mod vote_deactivate;
pub mod vote_initiate;
pub mod vote_set_weights;
pub mod withdraw_collateral;
pub mod withdraw_treasury;

// Glob re-exports so the `#[program]` macro sees each instruction's Accounts struct.
// (Emits a benign "ambiguous glob re-exports" warning for the shared `handler` name;
// handlers are always called fully-qualified, e.g. `initialize::handler`.)
pub use admin::*;
pub use close_stale_claim::*;
pub use confirm_swap::*;
pub use deactivate::*;
pub use extend_reservation::*;
pub use extend_timeout::*;
pub use initialize::*;
pub use mark_fulfilled::*;
pub use open_or_request::*;
pub use post_collateral::*;
pub use remove_quote::*;
pub use resolve_pool::*;
pub use set_quote::*;
pub use submit_swap_claim::*;
pub use timeout_swap::*;
pub use vote_activate::*;
pub use vote_deactivate::*;
pub use vote_initiate::*;
pub use vote_set_weights::*;
pub use withdraw_collateral::*;
pub use withdraw_treasury::*;
